version: '3'
services:
  web:
    container_name: web-container
    build: .
    image: my_app
    command: rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  redis:
    container_name: redis-container
    image: redis
